name: oggatonama
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0' # Adjust SDK constraint if needed

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.0 # Updated to latest version
  firebase_auth: ^5.5.0 # Updated to latest version
  cloud_firestore: ^5.6.4 # Updated to a compatible version
  get: ^4.6.6
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Updated to latest version
  url_launcher: ^6.1.7


flutter:
  uses-material-design: true