// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkEo-EvfkhBgo_EjD0SufA5RlmbETx08Q',
    appId: '1:133326199109:web:b7bc10c687805a4768c62c',
    messagingSenderId: '133326199109',
    projectId: 'oggatonama-591021',
    authDomain: 'oggatonama-591021.firebaseapp.com',
    storageBucket: 'oggatonama-591021.firebasestorage.app',
    measurementId: 'G-WT51JJ3T95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmcdPplrZIzgN_2jXkD9iHpnh2OCh4Wig',
    appId: '1:133326199109:android:eaade266b84e34f768c62c',
    messagingSenderId: '133326199109',
    projectId: 'oggatonama-591021',
    storageBucket: 'oggatonama-591021.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz2Wh6KUfr3pemmIAmOSb73NvJtC1ZeTk',
    appId: '1:133326199109:ios:4e94b896752faade68c62c',
    messagingSenderId: '133326199109',
    projectId: 'oggatonama-591021',
    storageBucket: 'oggatonama-591021.firebasestorage.app',
    iosBundleId: 'com.example.oggatonama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz2Wh6KUfr3pemmIAmOSb73NvJtC1ZeTk',
    appId: '1:133326199109:ios:4e94b896752faade68c62c',
    messagingSenderId: '133326199109',
    projectId: 'oggatonama-591021',
    storageBucket: 'oggatonama-591021.firebasestorage.app',
    iosBundleId: 'com.example.oggatonama',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkEo-EvfkhBgo_EjD0SufA5RlmbETx08Q',
    appId: '1:133326199109:web:f6868c036d9be85568c62c',
    messagingSenderId: '133326199109',
    projectId: 'oggatonama-591021',
    authDomain: 'oggatonama-591021.firebaseapp.com',
    storageBucket: 'oggatonama-591021.firebasestorage.app',
    measurementId: 'G-P0Z6XTWRPR',
  );
}
